# Generated by Django 3.2.6 on 2021-08-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0003_alter_author_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='action',
            field=models.CharField(default='Ver', max_length=45),
            preserve_default=False,
        ),
    ]
