# Generated by Django 3.2.6 on 2021-08-15 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0004_book_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='action',
        ),
    ]
