# Generated by Django 3.2.6 on 2021-08-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0005_remove_book_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='action',
            field=models.CharField(default='Ver', max_length=45),
        ),
    ]
